### ISSUE TITLE
Include folder came empty

### ISSUE THREAD

**Issue by kaustubhkabra** [ashtons/dcmtk-ios#1]
Hi there,
Great start for this library! I compiled using your library and build.sh for my system. lib files were there but include came empty under dependencies.
Also, when I imported libs under dependency/lib - v64 architecture support issue came up.
I agree this is WIP, just want to discuss and contribute.

**Comment by ashtons** [comment]
Hi, I've made additional commits today to correct the include folder missing problem.

Import and running on arm64 appears to work for me, although still not getting proper decoding of images yet.

**Comment by kaustubhkabra** [comment]
Hi, your updated commit solved the issue.
However, when I try to run in a sample project, it gives error - 
libc.h not found.
Any hint on possible solution ?

Update - Issue comes only while running on device, not on simulator.

**Comment by kaustubhkabra** [comment]
~~libc.h solved by including libc.h located in/usr/include/ it in my iPhoneOS SDK's usr/include folder~~

Now the error while running on device -

> Undefined symbols for architecture arm64:
>   "DcmFileFormat::loadFile(OFFilename const&, E_TransferSyntax, E_GrpLenEncoding, unsigned long, E_FileReadMode)", referenced from:
>       -[DicomViewerViewController onLoadDicom:] in DicomViewerViewController.o
> ld: symbol(s) not found for architecture arm64

##### Update - As such, sample project runs fine when arm64 is removed from valid architectures but that would not be acceptable if an app has to be submitted to App Store.

**Comment by ashtons** [comment]
I've changed how the script works, having much better success now using arm64

**Comment by kaustubhkabra** [comment]
Great, any success on showing image ?
I have posted query on dcmtk forum with trial code -
http://forum.dcmtk.org/viewtopic.php?f=1&t=4256
Just in case it helps.
Thanks !

**Comment by ashtons** [comment]
My included sample shows loading of the dictionary which is included in the project.
Give my sample a go and see if that works better for you

**Comment by kaustubhkabra** [comment]
Yup, it works :)
