### ISSUE TITLE
Binary file is not being generate

### ISSUE THREAD

**Issue by bankim** [ashtons/dcmtk-ios#2]
Hi,

I am trying to generate binary file from this project but it is not generating at all. Can you guys please help me on this with binary of this code or how can I generate it.

**Comment by ashtons** [comment]
I've updated the build script to use iOS SDK 9.1
It appears to now correctly generate the binary files again

**Comment by bankim** [comment]
Thanks for your quick response. Can you please update the sample project with latest binary, so I can start it from there.

**Comment by ashtons** [comment]
I've updated the sample project with the new binaries

**Comment by bankim** [comment]
Hi, Thanks for your reply. I have used the code snippet of echoscu, and it is working like a charm. But problem is that I am new into this and looking for some others stuffs like findscu, movescu, storescp, storescu and termscu. Can you have the snippet for those so I can use it directly in my objective-c code.

**Comment by bankim** [comment]
Hi,

I have an issue to get image from pacs server with this 3.6.0. So now I am looking for 3.6.1(snapshot) but I am not able to generate the binary. Can you please help me on this, for 3.6.0 you helped me a lot to get that.

Thanks a lot.
