### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by julialecat** [ashtons/dcmtk-ios#3]
Hi there,

I built the libraries for iOS 9.2 but when building my project with the generated .a files the following errors appear:

Undefined symbols for architecture arm64:
  "_deflate", referenced from:
      DcmZLibOutputFilter::compress(void const_, long, bool) in libdcmdata.a(dcostrmz.o)
  "_inflate", referenced from:
      DcmZLibInputFilter::decompress(void const_, long) in libdcmdata.a(dcistrmz.o)
  "_deflateInit2_", referenced from:
      DcmZLibOutputFilter::DcmZLibOutputFilter() in libdcmdata.a(dcostrmz.o)
  "_inflateEnd", referenced from:
      DcmZLibInputFilter::~DcmZLibInputFilter() in libdcmdata.a(dcistrmz.o)
  "_deflateEnd", referenced from:
      DcmZLibOutputFilter::~DcmZLibOutputFilter() in libdcmdata.a(dcostrmz.o)
  "_inflateInit_", referenced from:
      DcmZLibInputFilter::DcmZLibInputFilter() in libdcmdata.a(dcistrmz.o)
  "_inflateInit2_", referenced from:
      DcmZLibInputFilter::DcmZLibInputFilter() in libdcmdata.a(dcistrmz.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks in advance.

**Comment by ashtons** [comment]
You may be missing a reference to libz?

**Comment by julialecat** [comment]
That was it, I didn't realize the zlib dependency. Adding libz.tbd in Build Phases > Link Binary With Libraries did the trick.

Thank you very much.
