### ISSUE TITLE
DCMTK with ios-swift

### ISSUE THREAD

**Issue by sankardheksitulu** [ashtons/dcmtk-ios#4]
Actually I am not getting any link to contact with you here. The reason I am using Issues tab to reach you. :) I have used this library to work with objective-C but now I need to work on swift with this library. Can you please help me how can I achieve to build the binary for latest iOS and swift?

**Comment by ashtons** [comment]
Sorry I haven't attempted to use the library with Swift yet. 
The current project should work with iOS 9.2 SDK as far as I know

**Comment by sankardheksitulu** [comment]
Thanks for your quick response. 
Do you have any plan for using this library with Swift? Actually i have to work on Swift using this library. If you have any idea how to start and how i can build the library for Swift that will be very helpful for me.

**Comment by ashtons** [comment]
I've added an example Swift project that makes use of the libraries
