### ISSUE TITLE
Image view

### ISSUE THREAD

**Issue by deryck13** [ashtons/dcmtk-ios#5]
Hello Ashton. Love your work on this but i have one question. Have you tried to visualize  the .dcm image into a NSImageView? thanks :D

**Comment by ashtons** [comment]
No, but I'll run some tests and add an  example to the sample project when I get something that works.

**Comment by ashtons** [comment]
I've added an example of extracting a frame from a DCM image. The main thing is too make sure the dictionary is loaded.
