### ISSUE TITLE
Binaries for iOS version 8.0 

### ISSUE THREAD

**Issue by sankardheksitulu** [ashtons/dcmtk-ios#6]
how can I generate dcmtk binaries for iOS version 8.0? and is it possible??
Currently the binaries are for iOS version 9.3.

**Comment by ashtons** [comment]
You should be able to open the project file and set the target to a lower number.

**Comment by ghost** [comment]
Yes I did, I have changed the target to 8.0 but getting 200+ warnings saying that dcmtk binaries are not build for version 8.0.

**Comment by ashtons** [comment]
I think you are changing the example project with the prebuilt binaries, you need to change the main library project and rebuild the binaries, and then copy them into the example project

**Comment by russes** [comment]
There's an alternative build you can try.  You can read about it here:

http://forum.dcmtk.org/viewtopic.php?f=3&p=17872&sid=bc91a4e2cf4a9a39b9107a723ddcacce#p17872

You'll need to modify iOS.cmake slightly, to force the build to use iOS 8.4, by adding two lines to the file, after the message line I show below:

```
message (STATUS "Building for minimum iOS version: ${IOS_DEPLOYMENT_TARGET} (SDK version: ${IOS_SDK_VERSION})")

set (IOS_DEPLOYMENT_TARGET "8.4")
set (IOS_DEVELOPMENT_TARGET "8.4")
```

You'll also need to set the iOS version in your Xcode project to 8.4.

See if that will build for you.

**Comment by ghost** [comment]
Did not work by changing the main library project version. 
I did changed my xCode version to lower and generated binaries then it works. :)

Thanks @ashtons & @russes

**Comment by ashtons** [comment]
I've uploaded a change which should compile the libraries with target iOS 8
