### ISSUE TITLE
Build DCMTK 3.6.1

### ISSUE THREAD

**Issue by AngYu** [ashtons/dcmtk-ios#8]
Could you update DCMTK to 3.6.1?

or could you teach me how to replace dcmtk3.6.0 into dcmtk 3.6.1?

thanks for help.

**Comment by ashtons** [comment]
Hi, there is unfortunately no current plan to support 3.6.1.
Happy to accept any pull requests if you get it working though

**Comment by russes** [comment]
AngYu,

I have an alternative build of DCMTK 3.6.1 that you should be able to try.  You can look at this note in the DCMTK installation forum for instructions:

http://forum.dcmtk.org/viewtopic.php?f=3&t=3047&p=18140#p17872

This build has nothing to do with what ashtons has done, so work from a clean playpen area that won't disturb your current efforts.  

The "afab" branch should have the iOS build.

This version should be 3.6.1_DEV as of a couple of days ago.
